JFLAGS = -g
JC = javac
.SUFFIXES: .java .class
.java.class:
        $(JC) $(JFLAGS) $*.java

CLASSES = \
        termfreqp.java \
        termfreqs.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
        $(RM) *.class
        $(RM) doc1_terms_s.txt doc1_freqs_s.txt doc1_terms_p.txt doc1_freqs_p.txt
run:
        java termfreqp 2 doc1.txt doc1_terms_p.txt doc1_freq_p.txt
        java termfreqs doc1.txt doc1_terms_s.txt doc1_freqs_s.txt
